### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by elcolie** [fredeil/email-validator.dart#40]
`email_validator: '^1.0.6'1`

```bash
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:email_validator

For solutions, see https://dart.dev/go/unsound-null-safety
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:472:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:152:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:665:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:573:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1154:11)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

**Comment by fredeil** [comment]
You should update to the latest version @elcolie
